name: Build Wolf NGZ
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Packaging
        run: |
          mkdir -p Wolf/logos
          cp plugin.py Wolf/
          cp __init__.py Wolf/
          cp logos/*.png Wolf/logos/
          tar -cvf WOLF.SERVER.ngz Wolf/
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Wolf-Plugin-Package
          path: WOLF.SERVER.ngz
